apiVersion: apps/v1
kind: ReplicaSet
metadata:
  name: mysqldb-replica
  namespace: final
  labels:
    app.kubernetes.io/name: mysql
    app.kubernetes.io/component: backend
spec:
  replicas: 3
  selector:
    matchLabels:
      app.kubernetes.io/name: mysql
      app.kubernetes.io/component: backend
  template:
    metadata:
      labels:
        app.kubernetes.io/name: mysql
        app.kubernetes.io/component: backend
    spec:
      containers:
      - name: mysqldb-pod
        image: 209830628404.dkr.ecr.us-east-1.amazonaws.com/clo835_final_project_db:v1.0
        imagePullPolicy: Always
        ports:
        - containerPort: 3306
        env:
        - name: MYSQL_ROOT_PASSWORD
          value: "pw"
      imagePullSecrets:
        - name: regcred
